name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@3.04

      with:
        name: znak07/github_lesson3:${GITHUB_REF:11} 
        username: znak07
        password: ${{ secrets.DOCKER_PASSWORD }}
    
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
